//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleClient2.SecondWcf {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PositionModel", Namespace="http://schemas.datacontract.org/2004/07/WcfService")]
    [System.SerializableAttribute()]
    public partial class PositionModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double CostField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Amount {
            get {
                return this.AmountField;
            }
            set {
                if ((this.AmountField.Equals(value) != true)) {
                    this.AmountField = value;
                    this.RaisePropertyChanged("Amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Cost {
            get {
                return this.CostField;
            }
            set {
                if ((this.CostField.Equals(value) != true)) {
                    this.CostField = value;
                    this.RaisePropertyChanged("Cost");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SecondWcf.IWcfPositionService")]
    public interface IWcfPositionService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfPositionService/GetData2", ReplyAction="http://tempuri.org/IWcfPositionService/GetData2Response")]
        string GetData2(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfPositionService/GetAll", ReplyAction="http://tempuri.org/IWcfPositionService/GetAllResponse")]
        ConsoleClient2.SecondWcf.PositionModel[] GetAll(int databaseId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfPositionService/Create", ReplyAction="http://tempuri.org/IWcfPositionService/CreateResponse")]
        ConsoleClient2.SecondWcf.PositionModel Create(ConsoleClient2.SecondWcf.PositionModel entity, int databaseId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfPositionService/Update", ReplyAction="http://tempuri.org/IWcfPositionService/UpdateResponse")]
        void Update(ConsoleClient2.SecondWcf.PositionModel entity, int databaseId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfPositionService/Delete", ReplyAction="http://tempuri.org/IWcfPositionService/DeleteResponse")]
        void Delete(int employeeId, int databaseId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWcfPositionServiceChannel : ConsoleClient2.SecondWcf.IWcfPositionService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WcfPositionServiceClient : System.ServiceModel.ClientBase<ConsoleClient2.SecondWcf.IWcfPositionService>, ConsoleClient2.SecondWcf.IWcfPositionService {
        
        public WcfPositionServiceClient() {
        }
        
        public WcfPositionServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WcfPositionServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WcfPositionServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WcfPositionServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData2(int value) {
            return base.Channel.GetData2(value);
        }
        
        public ConsoleClient2.SecondWcf.PositionModel[] GetAll(int databaseId) {
            return base.Channel.GetAll(databaseId);
        }
        
        public ConsoleClient2.SecondWcf.PositionModel Create(ConsoleClient2.SecondWcf.PositionModel entity, int databaseId) {
            return base.Channel.Create(entity, databaseId);
        }
        
        public void Update(ConsoleClient2.SecondWcf.PositionModel entity, int databaseId) {
            base.Channel.Update(entity, databaseId);
        }
        
        public void Delete(int employeeId, int databaseId) {
            base.Channel.Delete(employeeId, databaseId);
        }
    }
}
