//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleClient2.SecondWcf {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SecondWcf.IWcfService2")]
    public interface IWcfService2 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfService2/GetData2", ReplyAction="http://tempuri.org/IWcfService2/GetData2Response")]
        string GetData2(int value);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWcfService2Channel : ConsoleClient2.SecondWcf.IWcfService2, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WcfService2Client : System.ServiceModel.ClientBase<ConsoleClient2.SecondWcf.IWcfService2>, ConsoleClient2.SecondWcf.IWcfService2 {
        
        public WcfService2Client() {
        }
        
        public WcfService2Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WcfService2Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WcfService2Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WcfService2Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData2(int value) {
            return base.Channel.GetData2(value);
        }
    }
}
