//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleClient2.FirstWcf {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FirstWcf.IWcfService1")]
    public interface IWcfService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfService1/GetData1", ReplyAction="http://tempuri.org/IWcfService1/GetData1Response")]
        string GetData1(int value);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWcfService1Channel : ConsoleClient2.FirstWcf.IWcfService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WcfService1Client : System.ServiceModel.ClientBase<ConsoleClient2.FirstWcf.IWcfService1>, ConsoleClient2.FirstWcf.IWcfService1 {
        
        public WcfService1Client() {
        }
        
        public WcfService1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WcfService1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WcfService1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WcfService1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData1(int value) {
            return base.Channel.GetData1(value);
        }
    }
}
